# Generated by Django 4.1.1 on 2022-11-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
    ]
